### PR TITLE
Blog redirect

### PR DESCRIPTION
**Pull request by Superior212**

### CODE REVIEW

**Comment by Superior212** [comment]
@Goodness5  kindly review and merge

**Comment by Goodness5** [comment]
@Superior212 theres a conflict please resolve them

**Comment by Superior212** [comment]
resolved @Goodness5

**Comment by Web3Bridge** [comment]
@Superior212 please fix deployment 
image
above is the deployment error

**Comment by Superior212** [comment]
check again @Goodness5 i didn't have anything to do with analytics but have installed

**Comment by Web3Bridge** [comment]
image
@Superior212 it's still failing 
try npm run build on local to be sure it's production ready

**Comment by Web3Bridge** [comment]
> @Goodness5 done, it building in my end

nice

**Pull request merged**
