### PR TITLE
chore: made the testimonial card component dynamic, so addding new te…

### PR DESCRIPTION
**Pull request by collinsadi**
**Title:** Enhance Testimonial Card Component for Dynamic Updates

**Description:**

This pull request introduces a dynamic feature to the Testimonial Card component. The component has been updated to handle new testimonials more efficiently, allowing for easy addition of new testimonials without requiring manual adjustments to the codebase.

**Changes Made:**
- Refactored the Testimonial Card component to be dynamic.
- Implemented a new structure for handling testimonial data.
- Updated related components and styles to accommodate the dynamic nature.

**Benefits:**
- Simplifies the process of adding new testimonials.
- Improves maintainability and scalability of the testimonial section.
- Reduces the need for manual updates when testimonials are added.

**updates**
- added my personal testimonial

### CODE REVIEW

**Comment by Web3Bridge** [comment]
@collinsadi find here the updated document for the About pages, the document will keep being updated for other part of the Website.  
https://docs.google.com/document/d/1ITqth8ESJzTimIVCYhxqSwFtekTuhX4-yZTQEhuDQ4M/edit?usp=sharing

**Comment by collinsadi** [comment]
@Web3Bridge I've made the update and opened a Pull Request

**Comment by Web3Bridge** [comment]
The code is not compiled on the build.
Check locally.
Error; Missing "key" prop for element in iterator  react/jsx-key

**Comment by collinsadi** [comment]
@Web3Bridge The issue with missing key props has been resolved, and the build has been tested locally with all functionality working as expected.

**Pull request merged**
